---
title: "Clases"
subtitle: "Consulta de fuentes y lectura numérica del mundo"
author: "Dra. Daniela Serrano Campos"
date: "`r format(Sys.Date(), '%d de %B de %Y')`"
output:
  html_document:
    toc: true
    toc_float: true
    collapsed: false
    number_sections: false
    toc_depth: 1
    theme: spacelab
    #code_folding: hide
---
<style type="text/css">


.navbar {
  background-color: #CD8C95; /* Cambia este valor para ajustar el color del cintillo */
  border-color: #8B5F65; /* Opcional: cambia también el color del borde si es necesario */
}

.navbar-default .navbar-nav > li > a {
  color: #8B5F65; /* Cambia este valor para ajustar el color del texto en las etiquetas de las secciones */
}

#TOC {
  color: #8B5F65; 
}

.list-group-item.active, .list-group-item.active:focus, .list-group-item.active:hover {
    z-index: 2;
    color: #8B5F65;
    background-color: #EEDFCC;
    border-color: #8B5F65;
}

/* Cambia el color del título */
h1.title {
  color: #8B5F65; /* Azul claro - puedes cambiar este color */
}

/* Cambia el color del subtítulo */
h4.subtitle {
  color: #8B5F65; /* Azul acero - puedes cambiar este color */
}

/* Opcional: Cambia el color del autor */
h5.author {
  color: #8B5F65; /* Azul pizarra medio - puedes cambiar este color */
}

/* Opcional: Cambia el color de la fecha */
h5.date {
  color: #8B5F65; /* Verde oscuro - puedes cambiar este color */
}

</style>

<div style="color:#8B5F65;">

```{r setup, include=FALSE}
knitr::opts_chunk$set(message=FALSE,warning=FALSE, cache=TRUE)
```
**Nota:** Iré agregando las presentaciones de las clases.


# 1. Clase 1. 8 de agosto. Introducción
[Hacer ejercicio de autoevaluación y subir a classroom](https://uapa.cuaieed.unam.mx/sites/default/files/minisite/static/5955012c-005c-4441-b3a3-e9868a0cf8d1/contenido/index.html) 
<br><br>
<br><br>

## Presentación
<iframe src="intro_met_ccss.html" style="width: 800px; height: 600px; border: none;"></iframe>

# 2. Clase 2. 12 de agosto. Introducción
[Hacer ejercicio de autoevaluación y subir a classroom](https://uapa.cuaieed.unam.mx/sites/default/files/minisite/static/5955012c-005c-4441-b3a3-e9868a0cf8d1/contenido/index.html) 
<br><br>
<br><br>
## Presentación 1
<iframe src="Gerring_2014_cap2.html" style="width: 800px; height: 600px; border: none;"></iframe>

## Presentación 2
<iframe src="Gerring_2014_cap3.html" style="width: 800px; height: 600px; border: none;"></iframe>