---
title: "marco_legal_politico_dfi"
# subtitle: "¿Quiénes son?"
# author: "Daniela Serrano Campos,<br>*investigadora I*"
# institute: "DGAI"
# date: "10/08/24"
output:
  xaringan::moon_reader:
    lib_dir: libs
    css:
      - default
      - rladies
      - rladies-fonts
      - custom-inegi.css #CSS personalizado
      # - inegi_fonts.css
    seal: false
    self_contained: true
    nature:
      highlightStyle: github
      highlightLines: true
      countIncrementalSlides: false
      ratio: "4:3"
---

```{r setup, include = FALSE}
# remotes::install_github("mitchelloharawild/icons")
# devtools::install_github("hadley/emo")
library(knitr)                              # paquete que trae funciones utiles para R Markdown
library(tidyverse)                          # paquete que trae varios paquetes comunes en el tidyverse
library(datos)                              # paquete que viene con datos populares traducidos al español :)
library(emo)                                # paquete para emojislibrary(knitr)
library(tidyverse)
library(xaringanExtra)
library(icons) # # install.packages("remotes"); remotes::install_github("mitchelloharawild/icons")
library(fontawesome)

knitr::opts_chunk$set(echo = FALSE,         # FALSE: los bloques de código NO se muestran
                      dpi = 300,            # asegura gráficos de alta resolución
                      warning = FALSE,      # los mensajes de advertencia NO se muestran
                      error = FALSE)        # los mensajes de error NO se muestran
```
class: middle, inverse, center

.pull-center[

# Principios rectores
**son el marco normativo más ampliamente reconocido para describir el desplazamiento interno.**
]

.left[

## En las Américas 

1. Afecta a un gran número de personas en las Américas, especialmente debido a los **conflictos armados, los desastres y la violencia generalizada.**     
2. Los países del norte de América Central y **México** se han visto particularmente afectados por la **violencia criminal**, principalmente relacionada con el *tráfico de drogas y la actividad de las pandillas*.   
3. La Organización de los Estados Americanos (OEA) ha reconocido la magnitud del problema al adoptar en 2009 la Resolución de la Asamblea General AG/RES 2417.   
4. Bajo el paraguas de la OEA, la Comisión Interamericana de Derechos Humanos (CIDH) y la Corte Interamericana de Derechos Humanos (Corte IDH) han desempeñado un papel esencial en el monitoreo, la promoción y la protección de los derechos de las personas desplazadas internamente. 

]
---








