---
title: "Módulo 1"
subtitle: "Definición de Desplazamiento Forzado Interno"
# author: "Dra. Daniela Serrano Campos"
# date: "`r format(Sys.Date(), '%d de %B de %Y')`"
output:
  html_document:
    toc: true
    toc_float: true
    collapsed: false
    number_sections: false
    toc_depth: 1
    theme: spacelab
    css: "assets/css/styles.css"
    #code_folding: hide
---
<style type="text/css">
.navbar {
  background-color: #0077C8 !important; /* Cambia este valor para ajustar el color del cintillo */
  border-color: #0077C8 !important; /* Opcional: cambia también el color del borde si es necesario */
}


TOC {
  color: #0077C8; 
}

.list-group-item.active, .list-group-item.active:focus, .list-group-item.active:hover {
    z-index: 2;
    color: #003057;
    background-color: #0077C8;
    border-color: #0077C8;
}

hr.cintillo {
  border: 3px solid #0077C8; /* Color y grosor del cintillo */
  margin: 20px 0; /* Espaciado arriba y abajo del cintillo */
}
</style>

<div style="color: #003057;">

```{r setup, include=FALSE}
knitr::opts_chunk$set(message=FALSE,warning=FALSE, cache=TRUE)
```
<hr style="border: 3px solid#0077C8;" />


# Lección 1. Bienvenida al módulo

Este módulo sirve como introducción al curso de e-learning de cinco partes sobre las Recomendaciones Internacionales sobre Estadísticas de Desplazados Internos (IRIS).
Después de completar este módulo, podrás:

- Comprender la importancia de las estadísticas nacionales sobre desplazados.
- Describir las aplicaciones de política y programación de las estadísticas sobre desplazamiento forzado. 
- Describir los desafíos recurrentes de datos.
- Definir estadísticas oficiales y datos operativos en contextos de desplazamiento forzado.
- Comprender el papel del Grupo de Expertos en Estadísticas de Refugiados, Desplazados Internos y Apátridas (EGRISS) y su contribución a la recopilación de datos sobre desplazamiento forzado.
- Definir poblaciones de desplazados internos.
- Resumir las fuentes de datos y la coordinación en contextos de violencia o desastres naturales u ocasionados por el ser humano. 

Te tomará aproximadamente 1 hora y 15 minutos completar este módulo.

Para comenzar, haz clic en el botón de Módulo en la parte superior.

<!-- Dentro del módulo, puedes navegar seleccionando una lección del menú a la izquierda o usando los enlaces de Lección Anterior/Siguiente Lección arriba y abajo de cada lección. -->
<br><br>

<hr style="border: 3px solid#0077C8;" />
# Lección 2. Importancia de las estadísticas de calidad de Desplazamiento Forzado Interno

El desplazamiento forzado es un fenómeno persistente que plantea desafíos humanitarios importantes. 

Se estima que a fines de 2022, 62.5 millones de personas fueron desplazadas por la fuerza en todo el mundo. Aunque solo representa 0.8 por ciento de la población de ese año, las personas desplazadas por la fuerza enfrentan numerosos desafíos sociales y económicos, incluida la pérdida de bienes y medios de vida, y necesitan de políticas públicas orientadas a la reconstrución de sus vidas.

El desarrollo de políticas destinadas a mejorar las condiciones socioeconómicas de las personas desplazadas internas requiere estadísticas confiables, comparables y oportunas sobre estas poblaciones.

Los datos también son necesarios para mejorar el uso de los recursos y las capacidades a fin de atender mejor las necesidades de estas poblaciones vulnerables. Las estadísticas producidas a nivel nacional son las más eficaces para fundamentar la respuesta nacional.
<br><br>

<hr style="border: 3px solid#0077C8;" />
# Lección 3. ¿Quiénes son las personas desplazadas internas?

Mira la presentación a continuación para obtener más información.

<iframe src="definicion_dfi.html" style="width: 800px; height: 600px; border: none;"></iframe>

<hr class="cintillo"/>

<iframe src="https://danielasercampos.shinyapps.io/quiz_prueba/" style="width: 800px; height: 800px; border: none;"></iframe>
<br><br>

<hr style="border: 3px solid#0077C8;" />

# Lección 4. Principales fuentes de datos 

Las IRIS presentan cuatro fuentes de datos principales que pueden utilizarse para producir estadísticas oficiales sobre personas en situación de desplazamiento forzado interno.

Además de las fuentes tradicionales conocidas (censo, encuestas y registros administrativos), consideran **la integración de datos como una forma de combinar una variedad de fuentes de datos para mejorar la calidad de las estadísticas.**


Cada fuente de datos tiene sus propias ventajas y limitaciones. Las IRIS contemplan una serie de enfoques y adaptaciones, como la inclusión de preguntas o módulos específicos, que se pueden aplicar a cada fuente de datos para ayudar a identificar grupos de población relevantes.

✔️ Ahora ya conoces las principales fuentes de datos para elaborar estadísticas oficiales y cómo utilizarlas. En la siguiente lección se expondrá la necesidad de coordinación nacional e internacional en materia de estadísticas sobre refugiados, desplazados internos y apatridia.

<br><br>
<hr style="border: 3px solid#0077C8;" />
# Lección 5. El papel de las Oficinas Nacionales de Estadística (ONE) en la coordinación 

Las ONE desempeñan un papel crucial en la coordinación para garantizar que se apliquen los estándares de datos y se mantenga la calidad.

<iframe src="fuentes_iris.html" style="width: 800px; height: 600px; border: none;"></iframe>


<hr class="cintillo"/>

<iframe src="https://danielasercampos.shinyapps.io/ones_coord/" style="width: 800px; height: 800px; border: none;"></iframe>
<br><br>

<hr style="border: 3px solid#0077C8;" />
# Lección 6. Recursos

##[Descargar Recursos PDF](https://github.com/Danserca/DFIM/blob/master/docs/recursos_m1.pdf)

<hr style="border: 3px solid#0077C8;" />
# ¿Qué sigue?

➡️ Módulo 2. Estadísticas sobre DFI: stock, flujo y caracterización. 

<br><br>
<br><br>
**Has llegado al final de este módulo. Esperamos que lo hayas disfrutado y te haya ayudado a comprender mejor la necesidad de contar con estadísticas oficiales sobre desplazamiento forzado.**
