---
title: "recomendaciones_finales"
# subtitle: "¿Quiénes son?"
# author: "Daniela Serrano Campos,<br>*investigadora I*"
# institute: "DGAI"
# date: "10/08/24"
output:
  xaringan::moon_reader:
    lib_dir: libs
    css:
      - default
      - rladies
      - rladies-fonts
      - custom-inegi.css #CSS personalizado
      # - inegi_fonts.css
    seal: false
    self_contained: true
    nature:
      highlightStyle: github
      highlightLines: true
      countIncrementalSlides: false
      ratio: "4:3"
---

```{r setup, include = FALSE}
# remotes::install_github("mitchelloharawild/icons")
# devtools::install_github("hadley/emo")
library(knitr)                              # paquete que trae funciones utiles para R Markdown
library(tidyverse)                          # paquete que trae varios paquetes comunes en el tidyverse
library(datos)                              # paquete que viene con datos populares traducidos al español :)
library(emo)                                # paquete para emojislibrary(knitr)
library(tidyverse)
library(xaringanExtra)
library(icons) # # install.packages("remotes"); remotes::install_github("mitchelloharawild/icons")
library(fontawesome)

knitr::opts_chunk$set(echo = FALSE,         # FALSE: los bloques de código NO se muestran
                      dpi = 300,            # asegura gráficos de alta resolución
                      warning = FALSE,      # los mensajes de advertencia NO se muestran
                      error = FALSE)        # los mensajes de error NO se muestran
```
class: middle, center, inverse
.left[


# Recomendaciones para la medición del DFI

- **Retos en la medición actual:**
  - Las fuentes de datos como el Censo 2020, ENVIPE, ENOE, y ENADID no logran medir el DFI de manera completa.
  - Cada fuente cubre solo una parte de la población, lo que limita la visión integral del fenómeno.
]
---
class: middle, center
.left[

# Propuesta de encuesta piloto

- **Objetivo:**
  - Considerar tanto experiencias objetivas como la percepción subjetiva de violencia.
  - Considerar capacitación para abordar el tema, ya que es sensible y susceptible de sesgos.

- **Enfoque:**
  - Explorar la exclusión de los adjetivos "forzado" y "obligado".
  - Permitir el registro de múltiples causas para el cambio de residencia.
  - Referencia a los módulos "H" e "I" de la Encuesta de Alta Frecuencia de Sudán del Sur (HFSSSD) para el diseño del cuestionario.
]
---
class: middle, center,inverse
.left[
##  **Enfoques para determinar la causalidad:**
 ### Percibida:
- **Ventajas:** 
  - Permite explorar las percepciones subjetivas de las personas, lo cual es fundamental para comprender sus miedos, preocupaciones y comportamientos.
- **Limitaciones:**
  - Sujeta a sesgos cognitivos y sociales, como la sobreestimación de ciertos riesgos o la influencia de los medios de comunicación.

### Objetiva:
- **Ventajas:**
  - Proporciona datos cuantitativos y confiables sobre la incidencia real de la violencia o victimización, lo que permite realizar análisis estadísticos y comparaciones entre grupos.
- **Limitaciones:**
  - Puede subestimar la violencia oculta o no denunciada, y no captura la dimensión emocional y psicológica de la experiencia.
]
---
class: middle, center
.left[
##  **Enfoques para determinar la causalidad:**
### Ambas:
- **Ventajas:**
  - Se complementan, ofreciendo una visión más completa y matizada del fenómeno. Permite identificar las discrepancias entre la percepción y los hechos de victimización, y explorar los factores que influyen en estas diferencias.
- **Limitaciones:**
  - Requiere un diseño de investigación más complejo y costoso.
]
---
class: middle, center, inverse

.pull-center[

# Recomendaciones para la Producción de Estadísticas de DFI
]

.left[
**1. Revisión de Cuestionarios y Preguntas**:
   - Permitir que los informantes puedan atribuir la migración a **más de una causa**.
   - Diferenciar entre **migración** y **desplazamiento forzado**, y explorar causas específicas como:
     - Inseguridad delictiva
     - Enfrentamientos entre organizaciones criminales
     - Inseguridad pública
     - Violaciones de derechos humanos

**2. Sobremuestreo de Municipios con Historial de DFI**:
   - Focalizar en municipios con historial de DFI asociado a la violencia para mejorar la representatividad y eficiencia del estudio.

]
---
class: middle, center, inverse

.pull-center[

# Recomendaciones para la Producción de Estadísticas de DFI
]

.left[
**3. Impacto y Variabilidad**:
   - Reconocer que el impacto de la violencia en el DFI varía según el tipo de municipio.
   - La **gran dispersión de datos** y los **valores atípicos** sugieren la necesidad de análisis más profundos.

**4. Orientación para Futuros Estudios**:
   - Utilizar estos hallazgos y sugerencias como **guía** para mejorar el diseño muestral y conceptual en futuros proyectos sobre DFI.  
   
**5. Coordinación**:  
   - Elaborar planes de trabajo conjuntos y establecer grupos de trabajo técnicos para mejorar las estadísticas sobre refugiados y desplazados internos.     
   - Formación de órganos de gobernanza técnica a nivel nacional para fortalecer las estadísticas sobre refugiados.    
   - Priorización de las estadísticas sobre desplazados internos en los sistemas nacionales de estadísticas.  
]


